FROM mcr.microsoft.com/playwright:v1.48.0-noble

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# install browsers
RUN npx playwright install --with-deps

CMD ["npm", "run", "test:e2e"]
